### ISSUE TITLE
Implement utility functions for SR quantities.

### ISSUE THREAD

**Issue by dtabell** [bmad-sim/BeamTracking.jl#15]
Place functions for computing beta, gamma, Brho, _etc._ in `utils.jl`.

**Comment by dtabell** [comment]
@DavidSagan and @mattsignorelli
It turns out (I should have remembered this) to be much better to
compute the various relativistic quantities starting from either the
kinetic energy, $E_\text{kin}$, or $\beta\gamma$. So the `beam` struct should store the
reference value of one of those quantities instead of $\beta_0$. I have a
slight preference for storing $(\beta\gamma)_0$—it is dimensionless—but I am
comfortable with either. Thoughts?

**Comment by dtabell** [comment]
On the other hand, storing the kinetic energy would likely make it
easier for people to debug their simulations.

**Comment by mattsignorelli** [comment]
My vote would be for the dimensionless quantity, so that all unitful quantities are contained in the `species` field

**Comment by dtabell** [comment]
I implemented functions to compute the following:
- [x] $\gamma$
- [x] $\gamma - 1$
- [x] $\beta$
- [x] $pc$
- [x] $E_\text{kin}$
- [x] $E_\text{tot}$
- [x] $B\rho$

One important difference from what we discussed: I made the arguments
$E_\text{rest}$ and $\beta\gamma$. In other words, I decided we should pass in $E_\text{rest}$ instead of a
`Species`. This choice of arguments will speed computations that require
computing one of the above quantities for an entire beam.

**Comment by DavidSagan** [comment]
@dtabell I have functions for computing these in AcceleratorLattice. We should combine and put in SimUtils
 or perhaps AtomicAndPhysicalConstants

**Comment by mattsignorelli** [comment]
I've modified the `beta_0` field to `beta_gamma_0` field in `Beam`

**Comment by dtabell** [comment]
I think we can close this issue.
